# -*- coding: utf-8 -*-
"""Car_detecting_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17J2fJa__kWNMasURLTThHsQau9CgsEce
"""

from google.colab import drive

drive.mount('/content/drive')

import zipfile
import os

zip_path = "/content/drive/MyDrive/master_dataset.zip"
extract_path = "/content"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir("/content/master_dataset"))



DATASET_DIR = "/content/master_dataset"

for cls in sorted(os.listdir(DATASET_DIR)):

    cls_path = os.path.join(DATASET_DIR, cls)

    if os.path.isdir(cls_path):
        print(cls, len(os.listdir(cls_path)))

import os
import shutil
import random

SOURCE_DIR = "/content/master_dataset"
BALANCED_DIR = "/content/balanced_dataset"

TARGET_PER_CLASS = 1500

if os.path.exists(BALANCED_DIR):
    shutil.rmtree(BALANCED_DIR)

os.makedirs(BALANCED_DIR, exist_ok=True)

valid_extensions = (".jpg", ".jpeg", ".png", ".webp")

for cls in sorted(os.listdir(SOURCE_DIR)):

    src_cls_path = os.path.join(SOURCE_DIR, cls)

    if not os.path.isdir(src_cls_path):
        continue

    dst_cls_path = os.path.join(BALANCED_DIR, cls)
    os.makedirs(dst_cls_path, exist_ok=True)

    images = [
        f for f in os.listdir(src_cls_path)
        if f.lower().endswith(valid_extensions)
    ]

    random.shuffle(images)

    if len(images) > TARGET_PER_CLASS:
        selected = images[:TARGET_PER_CLASS]
    else:
        selected = images

    for i, img in enumerate(selected):

        src_img = os.path.join(src_cls_path, img)

        ext = os.path.splitext(img)[1].lower()

        dst_img = os.path.join(
            dst_cls_path,
            f"{cls}_{i}{ext}"
        )

        shutil.copy2(src_img, dst_img)

    print(f"{cls}: {len(images)} -> {len(selected)}")

BALANCED_DIR = "/content/balanced_dataset"

for cls in sorted(os.listdir(BALANCED_DIR)):

    cls_path = os.path.join(BALANCED_DIR, cls)

    print(cls, len(os.listdir(cls_path)))

import os
import shutil
import random

BALANCED_DIR = "/content/balanced_dataset"
FINAL_DIR = "/content/final_dataset"

TRAIN_RATIO = 0.8

if os.path.exists(FINAL_DIR):
    shutil.rmtree(FINAL_DIR)

for split in ["train", "val"]:
    os.makedirs(os.path.join(FINAL_DIR, split), exist_ok=True)

valid_extensions = (".jpg", ".jpeg", ".png", ".webp")

for cls in sorted(os.listdir(BALANCED_DIR)):

    cls_path = os.path.join(BALANCED_DIR, cls)

    if not os.path.isdir(cls_path):
        continue

    images = [
        f for f in os.listdir(cls_path)
        if f.lower().endswith(valid_extensions)
    ]

    random.shuffle(images)

    train_size = int(len(images) * TRAIN_RATIO)

    train_images = images[:train_size]
    val_images = images[train_size:]

    for split, split_images in [
        ("train", train_images),
        ("val", val_images)
    ]:

        split_cls_dir = os.path.join(
            FINAL_DIR,
            split,
            cls
        )

        os.makedirs(split_cls_dir, exist_ok=True)

        for img in split_images:

            shutil.copy2(
                os.path.join(cls_path, img),
                os.path.join(split_cls_dir, img)
            )

    print(
        f"{cls}: "
        f"train={len(train_images)}, "
        f"val={len(val_images)}"
    )

FINAL_DIR = "/content/final_dataset"

for split in ["train", "val"]:

    print(f"\n--- {split.upper()} ---")

    split_dir = os.path.join(FINAL_DIR, split)

    for cls in sorted(os.listdir(split_dir)):

        cls_path = os.path.join(split_dir, cls)

        print(cls, len(os.listdir(cls_path)))

import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

!pip install timm
!pip install torchmetrics

import os
import torch
import timm
import numpy as np

from PIL import Image

from torch import nn
from torch.utils.data import DataLoader

from torchvision import datasets, transforms

from sklearn.metrics import (
    f1_score,
    classification_report,
    confusion_matrix
)

from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

TRAIN_DIR = "/content/final_dataset/train"
VAL_DIR = "/content/final_dataset/val"

train_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

val_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

train_dataset = datasets.ImageFolder(
    TRAIN_DIR,
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=val_transform
)

print(train_dataset.classes)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print(len(train_loader))
print(len(val_loader))

model = timm.create_model(
    "efficientnet_b0",
    pretrained=True,
    num_classes=8
)

model = model.to(device)

print("Model hazır 😈")

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-4,
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="max",
    factor=0.5,
    patience=2
)

scaler = torch.cuda.amp.GradScaler()

def train_one_epoch(model, loader):

    model.train()

    running_loss = 0

    all_preds = []
    all_labels = []

    for images, labels in tqdm(loader):

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast():

            outputs = model(images)

            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()

        scaler.step(optimizer)

        scaler.update()

        running_loss += loss.item()

        preds = outputs.argmax(dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    f1 = f1_score(
        all_labels,
        all_preds,
        average="macro"
    )

    return running_loss / len(loader), f1

def validate(model, loader):

    model.eval()

    running_loss = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():

        for images, labels in tqdm(loader):

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            running_loss += loss.item()

            preds = outputs.argmax(dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    f1 = f1_score(
        all_labels,
        all_preds,
        average="macro"
    )

    return (
        running_loss / len(loader),
        f1,
        all_preds,
        all_labels
    )

from PIL import Image
import os

BAD_FILES = []

DATASET_DIR = "/content/final_dataset"

for root, dirs, files in os.walk(DATASET_DIR):

    for file in files:

        path = os.path.join(root, file)

        try:
            img = Image.open(path)
            img.verify()

        except Exception:
            BAD_FILES.append(path)

print("Bozuk dosya sayısı:", len(BAD_FILES))

for f in BAD_FILES[:20]:
    print(f)

for f in BAD_FILES:
    os.remove(f)

print("Bozuk dosyalar silindi 😈")

train_dataset = datasets.ImageFolder(
    TRAIN_DIR,
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=val_transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

EPOCHS = 15

best_f1 = 0

train_history = []
val_history = []

for epoch in range(EPOCHS):

    print(f"\n======== EPOCH {epoch+1}/{EPOCHS} ========\n")

    train_loss, train_f1 = train_one_epoch(
        model,
        train_loader
    )

    val_loss, val_f1, val_preds, val_labels = validate(
        model,
        val_loader
    )

    scheduler.step(val_f1)

    train_history.append(train_f1)
    val_history.append(val_f1)

    print(f"\nTrain Loss: {train_loss:.4f}")
    print(f"Train Macro F1: {train_f1:.4f}")

    print(f"\nVal Loss: {val_loss:.4f}")
    print(f"Val Macro F1: {val_f1:.4f}")

    if val_f1 > best_f1:

        best_f1 = val_f1

        torch.save(
    model.state_dict(),
    "/content/drive/MyDrive/best_model.pth"
)

        print("\n🔥 BEST MODEL SAVED 🔥")

print(f"\n🏆 BEST VAL F1: {best_f1:.4f}")

import timm
import torch

model = timm.create_model(
    "efficientnet_b0",
    pretrained=False,
    num_classes=8
)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/best_model.pth")
)

model = model.to(device)

model.eval()

print("Model başarıyla yüklendi 🚀")

from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms

# class isimleri
class_names = [
    "F1-OPEN-WHEEL",
    "HATCHBACK",
    "MICRO",
    "PICK UP",
    "SEDAN",
    "STATION WAGON",
    "SUV",
    "VAN"
]

# transform
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

# test image yolu
img_path = "/content/test.jpg"   # BURAYI değiştireceğiz

# image aç
img = Image.open(img_path).convert("RGB")

# modele uygun hale getir
input_tensor = transform(img).unsqueeze(0).to(device)

# prediction
with torch.no_grad():
    outputs = model(input_tensor)
    pred = torch.argmax(outputs, dim=1).item()

predicted_class = class_names[pred]

# göster
plt.imshow(img)
plt.title(f"Tahmin: {predicted_class}")
plt.axis("off")

print("Tahmin edilen sınıf:", predicted_class)

from torchvision.datasets import ImageFolder

dataset = ImageFolder("/content/balanced_dataset")

print(dataset.class_to_idx)

import timm
import torch

model = timm.create_model(
    "efficientnet_b0",
    pretrained=False,
    num_classes=8
)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/best_model.pth")
)

model = model.to(device)

model.eval()

print("Model hazır 🚀")

from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms
import torch.nn.functional as F

# gerçek class sırası
class_names = [
    "F1-OPEN-WHEEL",
    "HATCHBACK",
    "MICRO",
    "PICK UP",
    "SEDAN",
    "STATION WAGON",
    "SUV",
    "VAN"
]

# inference transform
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# görsel yolu
img_path = "/content/test6.jpg"

# image aç
img = Image.open(img_path).convert("RGB")

# modele uygun tensor
input_tensor = transform(img).unsqueeze(0).to(device)

# prediction
with torch.no_grad():
    outputs = model(input_tensor)

    probs = F.softmax(outputs, dim=1)

top_prob, pred = torch.max(probs, dim=1)

predicted_class = class_names[pred.item()]
confidence = top_prob.item() * 100

# görsel göster
plt.imshow(img)
plt.title(f"{predicted_class} ({confidence:.2f}%)")
plt.axis("off")

print(f"Tahmin: {predicted_class}")
print(f"Güven: %{confidence:.2f}")

print("\nTüm olasılıklar:\n")

for i, class_name in enumerate(class_names):
    print(f"{class_name}: %{probs[0][i].item()*100:.2f}")

import torch
import time

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

import timm
model = timm.create_model(
    "efficientnet_b0",
    pretrained=False,
    num_classes=8
)

model = model.to(device)

model.load_state_dict(
    torch.load("/content/drive/MyDrive/best_model.pth")
)

model.eval()

print("Model başarıyla yüklendi 🚀")

from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms
import torch.nn.functional as F

# gerçek class sırası
class_names = [
    "F1-OPEN-WHEEL",
    "HATCHBACK",
    "MICRO",
    "PICK UP",
    "SEDAN",
    "STATION WAGON",
    "SUV",
    "VAN"
]

# inference transform
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# görsel yolu
img_path = "/content/van.jpg"

# image aç
img = Image.open(img_path).convert("RGB")

# modele uygun tensor
input_tensor = transform(img).unsqueeze(0).to(device)

# prediction
with torch.no_grad():
    outputs = model(input_tensor)

    probs = F.softmax(outputs, dim=1)

top_prob, pred = torch.max(probs, dim=1)
predicted_class = class_names[pred.item()]
confidence = top_prob.item() * 100

# görsel göster
plt.imshow(img)
plt.title(f"{predicted_class} ({confidence:.2f}%)")
plt.axis("off")

print(f"Tahmin: {predicted_class}")
print(f"Güven: %{confidence:.2f}")

print("\nTüm olasılıklar:\n")

for i, class_name in enumerate(class_names):
    print(f"{class_name}: %{probs[0][i].item()*100:.2f}")



