# -*- coding: utf-8 -*-
"""Training_notebook/n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mW4THFT_rnDI94NuIijRGQwvbh_wl_DM
"""

# =========================================================
# ADIM 1 — GOOGLE DRIVE BAĞLAMA
# =========================================================

from google.colab import drive
drive.mount('/content/drive')

# =========================================================
# ADIM 2 — GEREKLİ KÜTÜPHANELER
# =========================================================

!pip install timm -q

# =========================================================
# ADIM 3 — IMPORTLAR
# =========================================================

import os
import random
import shutil
import zipfile
import numpy as np
import pandas as pd
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

import timm

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import seaborn as sns
import matplotlib.pyplot as plt

# =========================================================
# ADIM 4 — GPU KONTROL
# =========================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

# =========================================================
# ADIM 5 — ZIP DOSYASINI ÇIKARMA
# =========================================================

ZIP_PATH = "/content/drive/MyDrive/master_dataset1.zip"

EXTRACT_PATH = "/content/raw_dataset"

with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
    zip_ref.extractall(EXTRACT_PATH)

print("Dataset çıkarıldı.")

# =========================================================
# ADIM 6 — DATASET PATH DÜZELTME
# =========================================================

EXTRACT_PATH = "/content/raw_dataset/master_dataset"

print(os.listdir(EXTRACT_PATH))

# =========================================================
# ADIM 6 — SINIFLARI KONTROL ETME
# =========================================================

classes = os.listdir(EXTRACT_PATH)

print(classes)

# =========================================================
# ADIM 7 — BOZUK GÖRSELLERİ TEMİZLEME
# =========================================================

removed = 0

for class_name in os.listdir(EXTRACT_PATH):

    class_path = os.path.join(EXTRACT_PATH, class_name)

    for image_name in os.listdir(class_path):

        image_path = os.path.join(class_path, image_name)

        try:
            img = Image.open(image_path)
            img.verify()

        except:
            removed += 1
            os.remove(image_path)

print("Silinen bozuk görsel:", removed)

# =========================================================
# ADIM 8 — SINIF BAŞINA MAX 1000 GÖRSEL AYARLAMA
# =========================================================

MAX_IMAGES = 1000

for class_name in os.listdir(EXTRACT_PATH):

    class_path = os.path.join(EXTRACT_PATH, class_name)

    images = os.listdir(class_path)

    random.shuffle(images)

    if len(images) > MAX_IMAGES:

        remove_images = images[MAX_IMAGES:]

        for img_name in remove_images:

            os.remove(os.path.join(class_path, img_name))

print("Dengeleme tamamlandı.")

# =========================================================
# ADIM 9 — TRAIN / VAL SPLIT OLUŞTURMA
# =========================================================

FINAL_DATASET = "/content/master_dataset1"

TRAIN_DIR = os.path.join(FINAL_DATASET, "train")
VAL_DIR = os.path.join(FINAL_DATASET, "val")

os.makedirs(TRAIN_DIR, exist_ok=True)
os.makedirs(VAL_DIR, exist_ok=True)

VAL_RATIO = 0.2

for class_name in os.listdir(EXTRACT_PATH):

    class_path = os.path.join(EXTRACT_PATH, class_name)

    images = os.listdir(class_path)

    random.shuffle(images)

    split_idx = int(len(images) * (1 - VAL_RATIO))

    train_images = images[:split_idx]
    val_images = images[split_idx:]

    os.makedirs(os.path.join(TRAIN_DIR, class_name), exist_ok=True)
    os.makedirs(os.path.join(VAL_DIR, class_name), exist_ok=True)

    for img_name in train_images:

        src = os.path.join(class_path, img_name)
        dst = os.path.join(TRAIN_DIR, class_name, img_name)

        shutil.copy(src, dst)

    for img_name in val_images:

        src = os.path.join(class_path, img_name)
        dst = os.path.join(VAL_DIR, class_name, img_name)

        shutil.copy(src, dst)

print("Train/Val split tamamlandı.")

# =========================================================
# ADIM 10 — AUGMENTATION VE TRANSFORMS
# =========================================================

train_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.RandomHorizontalFlip(),

    transforms.RandomRotation(10),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

val_transform = transforms.Compose([

    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# =========================================================
# ADIM 11 — DATASET VE DATALOADER
# =========================================================

train_dataset = datasets.ImageFolder(
    TRAIN_DIR,
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    VAL_DIR,
    transform=val_transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)

class_names = train_dataset.classes

print(class_names)

print(train_dataset.class_to_idx)

# =========================================================
# ADIM 12 — MODEL OLUŞTURMA
# =========================================================

model = timm.create_model(
    "efficientnet_b0",
    pretrained=True,
    num_classes=len(class_names)
)

model = model.to(device)

# =========================================================
# ADIM 13 — LOSS VE OPTIMIZER
# =========================================================

criterion = nn.CrossEntropyLoss(
    label_smoothing=0.1
)

optimizer = optim.AdamW(
    model.parameters(),
    lr=0.0001
)

# =========================================================
# ADIM 14 — TRAINING DEĞİŞKENLERİ
# =========================================================

EPOCHS = 15

best_f1 = 0.0

train_losses = []
val_losses = []

train_accs = []
val_accs = []

train_f1s = []
val_f1s = []

# =========================================================
# ADIM 15 — TRAINING LOOP
# =========================================================

for epoch in range(EPOCHS):

    print(f"\nEpoch {epoch+1}/{EPOCHS}")

    # =========================
    # TRAIN
    # =========================

    model.train()

    running_loss = 0

    train_preds = []
    train_labels = []

    for images, labels in tqdm(train_loader):

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)

        train_preds.extend(preds.cpu().numpy())
        train_labels.extend(labels.cpu().numpy())

    train_loss = running_loss / len(train_loader)

    train_acc = accuracy_score(train_labels, train_preds)

    train_f1 = f1_score(
        train_labels,
        train_preds,
        average="macro"
    )

    # =========================
    # VALIDATION
    # =========================

    model.eval()

    val_running_loss = 0

    val_preds = []
    val_labels = []

    with torch.no_grad():

        for images, labels in tqdm(val_loader):

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            val_running_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)

            val_preds.extend(preds.cpu().numpy())
            val_labels.extend(labels.cpu().numpy())

    val_loss = val_running_loss / len(val_loader)

    val_acc = accuracy_score(val_labels, val_preds)

    val_f1 = f1_score(
        val_labels,
        val_preds,
        average="macro"
    )

    # =========================
    # SAVE BEST MODEL
    # =========================

    if val_f1 > best_f1:

        best_f1 = val_f1

        torch.save(
            model.state_dict(),
            "/content/best_model.pth"
        )

        print("BEST MODEL SAVED")

    # =========================
    # LOGS
    # =========================

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    train_accs.append(train_acc)
    val_accs.append(val_acc)

    train_f1s.append(train_f1)
    val_f1s.append(val_f1)

    print(f"Train Loss: {train_loss:.4f}")
    print(f"Val Loss: {val_loss:.4f}")

    print(f"Train Acc: {train_acc:.4f}")
    print(f"Val Acc: {val_acc:.4f}")

    print(f"Train F1: {train_f1:.4f}")
    print(f"Val F1: {val_f1:.4f}")

# =========================================================
# ADIM 16 — BEST MODEL LOAD
# =========================================================

best_model = timm.create_model(
    "efficientnet_b0",
    pretrained=False,
    num_classes=len(class_names)
)

best_model.load_state_dict(
    torch.load("/content/best_model.pth")
)

best_model = best_model.to(device)

best_model.eval()

# =========================================================
# ADIM 17 — FINAL VALIDATION SONUÇLARI
# =========================================================

all_preds = []
all_labels = []

with torch.no_grad():

    for images, labels in tqdm(val_loader):

        images = images.to(device)

        outputs = best_model(images)

        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())

# =========================================================
# ADIM 18 — METRİKLER
# =========================================================

acc = accuracy_score(all_labels, all_preds)

f1 = f1_score(
    all_labels,
    all_preds,
    average="macro"
)

print("Accuracy:", acc)

print("Macro F1:", f1)

# =========================================================
# ADIM 19 — CLASSIFICATION REPORT
# =========================================================

print(classification_report(
    all_labels,
    all_preds,
    target_names=class_names,
    digits=4
))

# =========================================================
# ADIM 20 — CONFUSION MATRIX
# =========================================================

cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(12, 10))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted")
plt.ylabel("True")

plt.title("Confusion Matrix")

plt.show()

# =========================================================
# ADIM 21 — NORMALIZED CONFUSION MATRIX
# =========================================================

cm_norm = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(12, 10))

sns.heatmap(
    cm_norm,
    annot=True,
    fmt=".2f",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted")
plt.ylabel("True")

plt.title("Normalized Confusion Matrix")

plt.show()

# =========================================================
# ADIM 22 — LOSS GRAPH
# =========================================================

plt.figure(figsize=(10, 5))

plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Val Loss")

plt.legend()

plt.title("Loss Graph")

plt.show()

# =========================================================
# ADIM 23 — ACCURACY GRAPH
# =========================================================

plt.figure(figsize=(10, 5))

plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Val Accuracy")

plt.legend()

plt.title("Accuracy Graph")

plt.show()

# =========================================================
# ADIM 24 — F1 GRAPH
# =========================================================

plt.figure(figsize=(10, 5))

plt.plot(train_f1s, label="Train F1")
plt.plot(val_f1s, label="Val F1")

plt.legend()

plt.title("F1 Graph")

plt.show()

# =========================================================
# ADIM 25 — MODELİ DRIVE'A KAYDETME
# =========================================================

SAVE_PATH = "/content/drive/MyDrive/best_model2.pth"

shutil.copy(
    "/content/best_model.pth",
    SAVE_PATH
)

print("Model drive'a kaydedildi.")





